apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "traefik2025.name" . }}-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "traefik2025.name" . }}-frontend-service
                port:
                  number: {{ .Values.service.frontendPort }}