apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik2025.name" . }}-frontend-service
  labels:
    app: {{ include "traefik2025.name" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "traefik2025.name" . }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.container.frontendPort }}
