variable "eks_cluster_name" {}
variable "eks_version" {}
variable "eks_node_group_name" {}
variable "eks_instance_type" {}
variable "eks_key_pair" {}
variable "aws_region" {}
variable "db_name" {}
variable "db_username" {}
variable "db_instance_class" {}