- name: Créer le namespace gitlab
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: gitlab

- name: Créer le ServiceAccount
  kubernetes.core.k8s:
    state: present
    namespace: gitlab
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: gitlab-runner-sa

- name: Ajouter ClusterRole Admin au Service Account Gitlab
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: gitlab-runner-crb
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: gitlab-runner-sa
          namespace: gitlab

- name: Ajouter le repo Helm GitLab
  community.kubernetes.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io

- name: Installer GitLab Runner
  community.kubernetes.helm:
    name: gitlab-runner
    chart_ref: gitlab/gitlab-runner
    release_namespace: gitlab
    values:
      gitlabUrl: "https://gitlab.com/"
      runnerRegistrationToken: "{{ gitlab_runner_registration_token }}"
      rbac:
        create: false
      serviceAccount:
        create: false
        name: gitlab-runner-sa
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      runners:
        config: |
          [[runners]]
            [runners.kubernetes]
              helper_image = "gitlab/gitlab-runner-helper:arm64-latest"
              privileged = true
              cpu_request = "100m"
              memory_request = "128Mi"
            [[runners.kubernetes.volumes.empty_dir]]
              name = "docker-certs"
              mount_path = "/certs/client"
              medium = "Memory"