---
- name: Générer le dump SQL
  template:
    src: ../templates/dump_traefik2025.sql.j2
    dest: /tmp/dump.sql
    mode: '0600'

- name: Restaurer la base de données depuis le cluster
  shell: |
    kubectl delete pod psql-restore --ignore-not-found
    kubectl run psql-restore --image=postgres:16 --restart=Never --env="PGPASSWORD={{ db_password }}" -- sleep 3600
    kubectl cp /tmp/dump.sql psql-restore:/tmp/dump.sql
    kubectl exec psql-restore -- psql -h "{{ rds_endpoint }}" -U "{{ db_username }}" -d postgres -f /tmp/dump.sql
    kubectl delete pod psql-restore
  args:
    executable: /bin/bash

- name: Nettoyer
  file:
    path: /tmp/dump.sql
    state: absent
