---
- name: Ajouter le repo Helm Prometheus Community
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Installer kube-prometheus-stack
  community.kubernetes.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    values:
      prometheus:
        prometheusSpec:
          retention: 7d
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 5Gi
      grafana:
        adminPassword: "{{ grafana_admin_password | default('admin') }}"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        persistence:
          enabled: true
          size: 1Gi
        ingress:
          enabled: false
      alertmanager:
        alertmanagerSpec:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      kubeStateMetrics:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      nodeExporter:
        resources:
          requests:
            cpu: 10m
            memory: 24Mi
          limits:
            cpu: 100m
            memory: 64Mi