---
- name: Ajouter le repo Helm Grafana
  community.kubernetes.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Installer Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    release_namespace: monitoring
    create_namespace: true
    values:
      deploymentMode: SingleBinary
      singleBinary:
        replicas: 1
      read:
        replicas: 0
      write:
        replicas: 0
      backend:
        replicas: 0
      chunksCache:
        enabled: false
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        storage:
          type: filesystem
        schemaConfig:
          configs:
            - from: "2024-01-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: index_
                period: 24h

- name: Installer Promtail
  community.kubernetes.helm:
    name: promtail
    chart_ref: grafana/promtail
    release_namespace: monitoring
    values:
      config:
        clients:
          - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push