apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik2025.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "traefik2025.name" . }}-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "traefik2025.name" . }}-backend
    spec:
      containers:
        - name: {{ include "traefik2025.name" . }}-backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
