apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  FIRST_SUPERUSER: {{ .Values.database.superuserid | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.database.superuserpwd | quote }}
  SECRET_KEY: {{ .Values.secret_key | quote }}
