- name: Déployer Traefik, GitLab Runner et Monitoring sur EKS
  hosts: localhost
  connection: local
  tasks:
    # === TRAEFIK ===
    - name: Ajouter le repo Helm Traefik
      community.kubernetes.helm_repository:
        name: traefik
        repo_url: https://traefik.github.io/charts

    - name: Installer Traefik
      community.kubernetes.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: traefik
        create_namespace: true
        values:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

    # === GITLAB RUNNER ===
    - name: Créer le namespace gitlab
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: gitlab

    - name: Créer le ServiceAccount
      kubernetes.core.k8s:
        state: present
        namespace: gitlab
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: gitlab-runner-sa

    - name: Ajouter ClusterRole Admin au Service Account Gitlab
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: gitlab-runner-crb
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - kind: ServiceAccount
              name: gitlab-runner-sa
              namespace: gitlab

    - name: Ajouter le repo Helm GitLab
      community.kubernetes.helm_repository:
        name: gitlab
        repo_url: https://charts.gitlab.io

    - name: Installer GitLab Runner
      community.kubernetes.helm:
        name: gitlab-runner
        chart_ref: gitlab/gitlab-runner
        release_namespace: gitlab
        values:
          gitlabUrl: "https://gitlab.com/"
          runnerRegistrationToken: "{{ gitlab_runner_registration_token }}"
          rbac:
            create: false
          serviceAccount:
            create: false
            name: gitlab-runner-sa
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          runners:
            config: |
              [[runners]]
                [runners.kubernetes]
                  helper_image = "gitlab/gitlab-runner-helper:arm64-latest"
                  privileged = true
                  cpu_request = "100m"
                  memory_request = "128Mi"
                [[runners.kubernetes.volumes.empty_dir]]
                  name = "docker-certs"
                  mount_path = "/certs/client"
                  medium = "Memory"

    # === MONITORING: PROMETHEUS + GRAFANA ===
    - name: Ajouter le repo Helm Prometheus Community
      community.kubernetes.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Installer kube-prometheus-stack
      community.kubernetes.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          prometheus:
            prometheusSpec:
              retention: 7d
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: [ "ReadWriteOnce" ]
                    resources:
                      requests:
                        storage: 5Gi
          grafana:
            adminPassword: "{{ grafana_admin_password | default('admin') }}"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            persistence:
              enabled: true
              size: 1Gi
            ingress:
              enabled: false
          alertmanager:
            alertmanagerSpec:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
          kubeStateMetrics:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 64Mi
          nodeExporter:
            resources:
              requests:
                cpu: 10m
                memory: 24Mi
              limits:
                cpu: 100m
                memory: 64Mi

    # === MONITORING: LOKI (LOGS) ===
    - name: Ajouter le repo Helm Grafana
      community.kubernetes.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Installer Loki
      kubernetes.core.helm:
        name: loki
        chart_ref: grafana/loki
        release_namespace: monitoring
        create_namespace: true
        values:
          deploymentMode: SingleBinary
          singleBinary:
            replicas: 1
          read:
            replicas: 0
          write:
            replicas: 0
          backend:
            replicas: 0
          chunksCache:
            enabled: false
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            storage:
              type: filesystem
            schemaConfig:
              configs:
                - from: "2024-01-01"
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: index_
                    period: 24h

    - name: Installer Promtail
      community.kubernetes.helm:
        name: promtail
        chart_ref: grafana/promtail
        release_namespace: monitoring
        values:
          config:
            clients:
              - url: http://loki:3100/loki/api/v1/push