replicaCount: 1

app:
  nodeEnv: dev
  viteApiUrl: http://dev.api.fsci2025.ip-ddns.com

image:
  repository: fsci2025/traefik2025-frontend
  tag: latest

service:
  frontendPort: 80

container:
  frontendPort: 80

ingress:
  className: traefik
  host: dev.fsci2025.ip-ddns.com
